"""
Unit tests for BookExporter class.

Tests the book metadata calculation and export functionality for
plain text, markdown, and JSON formats.

Requirements: 14.6, 14.7, 15.10
"""
import json
from datetime import datetime, timezone

import pytest

try:
    from backend.core.book_exporter import BookExporter
    from backend.core.data_models import BookMetadata, Chapter, Scene, SceneType
except ImportError:
    from core.book_exporter import BookExporter
    from core.data_models import BookMetadata, Chapter, Scene, SceneType


# ------------------------------------------------------------------ #
# Fixtures                                                             #
# ------------------------------------------------------------------ #


@pytest.fixture
def sample_scenes():
    """Create sample scenes for testing."""
    return [
        Scene(
            scene_num=1,
            scene_type=SceneType.ACTION,
            content="The protagonist rushed through the crowded marketplace, dodging vendors and carts.",
            word_count=12,
        ),
        Scene(
            scene_num=2,
            scene_type=SceneType.DIALOGUE,
            content='"Where is the artifact?" demanded the antagonist. "I will never tell you," replied the hero.',
            word_count=17,
        ),
        Scene(
            scene_num=3,
            scene_type=SceneType.INTROSPECTION,
            content="The hero wondered if this was the right path. Doubt crept into their mind.",
            word_count=16,
        ),
    ]


@pytest.fixture
def sample_chapters(sample_scenes):
    """Create sample chapters for testing."""
    return [
        Chapter(
            chapter_num=1,
            title="Chapter 1: The Beginning",
            scenes=sample_scenes,
            word_count=45,
            summary="The hero begins their journey in the marketplace.",
        ),
        Chapter(
            chapter_num=2,
            title="Chapter 2: The Confrontation",
            scenes=sample_scenes[:2],  # Only first 2 scenes
            word_count=29,
            summary="The hero confronts the antagonist.",
        ),
    ]


@pytest.fixture
def sample_metadata():
    """Create sample book metadata for testing."""
    return BookMetadata(
        title="The Test Book",
        author_attribution="Generated by SCRIPTY",
        genre="Historical Fiction",
        total_word_count=1000,
        chapter_count=2,
        scene_count=5,
        reading_time_minutes=5,
        table_of_contents=[
            (0, "Prologue"),
            (1, "Chapter 1: The Beginning"),
            (2, "Chapter 2: The Confrontation"),
            (3, "Epilogue"),
        ],
        generation_timestamp=datetime(2024, 1, 15, 10, 30, 0, tzinfo=timezone.utc),
    )


@pytest.fixture
def exporter():
    """Create a BookExporter instance."""
    return BookExporter()


# ------------------------------------------------------------------ #
# Metadata calculation tests                                           #
# ------------------------------------------------------------------ #


def test_calculate_word_count_with_all_sections(sample_chapters):
    """Test word count calculation with prologue, chapters, and epilogue."""
    prologue = "This is a prologue with ten words in it total."
    epilogue = "This is an epilogue with ten words in it total."
    
    total = BookExporter.calculate_word_count(prologue, sample_chapters, epilogue)
    
    # prologue: 10 words
    # chapter 1: 45 words
    # chapter 2: 29 words
    # epilogue: 10 words
    # total: 94 words
    assert total == 94


def test_calculate_word_count_without_prologue(sample_chapters):
    """Test word count calculation without prologue."""
    epilogue = "This is an epilogue with ten words in it total."
    
    total = BookExporter.calculate_word_count(None, sample_chapters, epilogue)
    
    # chapter 1: 45 words
    # chapter 2: 29 words
    # epilogue: 10 words
    # total: 84 words
    assert total == 84


def test_calculate_word_count_without_epilogue(sample_chapters):
    """Test word count calculation without epilogue."""
    prologue = "This is a prologue with ten words in it total."
    
    total = BookExporter.calculate_word_count(prologue, sample_chapters, None)
    
    # prologue: 10 words
    # chapter 1: 45 words
    # chapter 2: 29 words
    # total: 84 words
    assert total == 84


def test_calculate_word_count_chapters_only(sample_chapters):
    """Test word count calculation with only chapters."""
    total = BookExporter.calculate_word_count(None, sample_chapters, None)
    
    # chapter 1: 45 words
    # chapter 2: 29 words
    # total: 74 words
    assert total == 74


def test_calculate_reading_time_standard():
    """Test reading time calculation for standard word count."""
    # 1000 words at 200 wpm = 5 minutes
    reading_time = BookExporter.calculate_reading_time(1000)
    assert reading_time == 5


def test_calculate_reading_time_large_book():
    """Test reading time calculation for large book."""
    # 50000 words at 200 wpm = 250 minutes
    reading_time = BookExporter.calculate_reading_time(50000)
    assert reading_time == 250


def test_calculate_reading_time_minimum():
    """Test reading time calculation returns minimum of 1 minute."""
    # Very short text should still return 1 minute
    reading_time = BookExporter.calculate_reading_time(50)
    assert reading_time == 1
    
    reading_time = BookExporter.calculate_reading_time(0)
    assert reading_time == 1


def test_generate_table_of_contents_with_all_sections(sample_chapters):
    """Test table of contents generation with prologue and epilogue."""
    toc = BookExporter.generate_table_of_contents(
        sample_chapters,
        include_prologue=True,
        include_epilogue=True,
    )
    
    assert len(toc) == 4
    assert toc[0] == (0, "Prologue")
    assert toc[1] == (1, "Chapter 1: The Beginning")
    assert toc[2] == (2, "Chapter 2: The Confrontation")
    assert toc[3] == (3, "Epilogue")


def test_generate_table_of_contents_chapters_only(sample_chapters):
    """Test table of contents generation with only chapters."""
    toc = BookExporter.generate_table_of_contents(
        sample_chapters,
        include_prologue=False,
        include_epilogue=False,
    )
    
    assert len(toc) == 2
    assert toc[0] == (1, "Chapter 1: The Beginning")
    assert toc[1] == (2, "Chapter 2: The Confrontation")


def test_generate_table_of_contents_with_prologue_only(sample_chapters):
    """Test table of contents generation with prologue only."""
    toc = BookExporter.generate_table_of_contents(
        sample_chapters,
        include_prologue=True,
        include_epilogue=False,
    )
    
    assert len(toc) == 3
    assert toc[0] == (0, "Prologue")
    assert toc[1] == (1, "Chapter 1: The Beginning")
    assert toc[2] == (2, "Chapter 2: The Confrontation")


# ------------------------------------------------------------------ #
# Plain text export tests                                              #
# ------------------------------------------------------------------ #


def test_export_plain_text_structure(exporter, sample_metadata, sample_chapters):
    """Test plain text export has correct structure."""
    prologue = "This is the prologue text."
    epilogue = "This is the epilogue text."
    
    result = exporter.export_plain_text(
        sample_metadata,
        sample_chapters,
        prologue,
        epilogue,
    )
    
    # Check that key sections are present
    assert "THE TEST BOOK" in result
    assert "By: Generated by SCRIPTY" in result
    assert "Genre: Historical Fiction" in result
    assert "Total words: 1,000" in result
    assert "Estimated reading time: 5 minutes" in result
    assert "TABLE OF CONTENTS" in result
    assert "Prologue" in result
    assert "CHAPTER 1: THE BEGINNING" in result
    assert "CHAPTER 2: THE CONFRONTATION" in result
    assert "This is the prologue text." in result
    assert "This is the epilogue text." in result


def test_export_plain_text_includes_scenes(exporter, sample_metadata, sample_chapters):
    """Test plain text export includes scene content."""
    result = exporter.export_plain_text(sample_metadata, sample_chapters)
    
    # Check that scene content is present
    assert "The protagonist rushed through the crowded marketplace" in result
    assert '"Where is the artifact?"' in result
    assert "The hero wondered if this was the right path" in result


def test_export_plain_text_includes_word_counts(exporter, sample_metadata, sample_chapters):
    """Test plain text export includes chapter word counts."""
    result = exporter.export_plain_text(sample_metadata, sample_chapters)
    
    assert "[Chapter word count: 45]" in result
    assert "[Chapter word count: 29]" in result


# ------------------------------------------------------------------ #
# Markdown export tests                                                #
# ------------------------------------------------------------------ #


def test_export_markdown_structure(exporter, sample_metadata, sample_chapters):
    """Test markdown export has correct structure."""
    prologue = "This is the prologue text."
    epilogue = "This is the epilogue text."
    
    result = exporter.export_markdown(
        sample_metadata,
        sample_chapters,
        prologue,
        epilogue,
    )
    
    # Check markdown headers
    assert "# The Test Book" in result
    assert "## Table of Contents" in result
    assert "## Prologue" in result
    assert "## Chapter 1: The Beginning" in result
    assert "## Chapter 2: The Confrontation" in result
    assert "## Epilogue" in result
    
    # Check metadata formatting
    assert "**Author:** Generated by SCRIPTY" in result
    assert "**Genre:** Historical Fiction" in result
    assert "**Total words:** 1,000" in result


def test_export_markdown_table_of_contents_links(exporter, sample_metadata, sample_chapters):
    """Test markdown export includes clickable TOC links."""
    result = exporter.export_markdown(sample_metadata, sample_chapters)
    
    # Check for markdown anchor links
    assert "[Prologue](#prologue)" in result
    assert "[Chapter 1: The Beginning](#chapter-1-the-beginning)" in result
    assert "[Chapter 2: The Confrontation](#chapter-2-the-confrontation)" in result


def test_export_markdown_scene_headings(exporter, sample_metadata, sample_chapters):
    """Test markdown export includes scene headings."""
    result = exporter.export_markdown(sample_metadata, sample_chapters)
    
    # Check for scene headings
    assert "### Scene 1 — Action" in result
    assert "### Scene 2 — Dialogue" in result
    assert "### Scene 3 — Introspection" in result


def test_export_markdown_preserves_paragraphs(exporter, sample_metadata, sample_chapters):
    """Test markdown export preserves paragraph breaks."""
    prologue = "First paragraph.\n\nSecond paragraph."
    
    result = exporter.export_markdown(sample_metadata, sample_chapters, prologue=prologue)
    
    # Both paragraphs should be present
    assert "First paragraph." in result
    assert "Second paragraph." in result


# ------------------------------------------------------------------ #
# JSON export tests                                                    #
# ------------------------------------------------------------------ #


def test_export_json_structure(exporter, sample_metadata, sample_chapters):
    """Test JSON export has correct structure."""
    prologue = "This is the prologue text."
    epilogue = "This is the epilogue text."
    
    result = exporter.export_json(
        sample_metadata,
        sample_chapters,
        prologue,
        epilogue,
    )
    
    # Parse JSON to verify structure
    data = json.loads(result)
    
    assert "metadata" in data
    assert "prologue" in data
    assert "chapters" in data
    assert "epilogue" in data
    
    assert data["prologue"] == prologue
    assert data["epilogue"] == epilogue


def test_export_json_metadata_fields(exporter, sample_metadata, sample_chapters):
    """Test JSON export includes all metadata fields."""
    result = exporter.export_json(sample_metadata, sample_chapters)
    data = json.loads(result)
    
    metadata = data["metadata"]
    assert metadata["title"] == "The Test Book"
    assert metadata["author_attribution"] == "Generated by SCRIPTY"
    assert metadata["genre"] == "Historical Fiction"
    assert metadata["total_word_count"] == 1000
    assert metadata["chapter_count"] == 2
    assert metadata["scene_count"] == 5
    assert metadata["reading_time_minutes"] == 5
    assert metadata["generation_timestamp"] == "2024-01-15T10:30:00+00:00"


def test_export_json_table_of_contents(exporter, sample_metadata, sample_chapters):
    """Test JSON export includes table of contents."""
    result = exporter.export_json(sample_metadata, sample_chapters)
    data = json.loads(result)
    
    toc = data["metadata"]["table_of_contents"]
    assert len(toc) == 4
    assert toc[0] == {"entry_num": 0, "title": "Prologue"}
    assert toc[1] == {"entry_num": 1, "title": "Chapter 1: The Beginning"}
    assert toc[2] == {"entry_num": 2, "title": "Chapter 2: The Confrontation"}
    assert toc[3] == {"entry_num": 3, "title": "Epilogue"}


def test_export_json_chapters_structure(exporter, sample_metadata, sample_chapters):
    """Test JSON export includes chapter structure."""
    result = exporter.export_json(sample_metadata, sample_chapters)
    data = json.loads(result)
    
    chapters = data["chapters"]
    assert len(chapters) == 2
    
    # Check first chapter
    ch1 = chapters[0]
    assert ch1["chapter_num"] == 1
    assert ch1["title"] == "Chapter 1: The Beginning"
    assert ch1["word_count"] == 45
    assert ch1["summary"] == "The hero begins their journey in the marketplace."
    assert len(ch1["scenes"]) == 3


def test_export_json_scenes_structure(exporter, sample_metadata, sample_chapters):
    """Test JSON export includes scene structure."""
    result = exporter.export_json(sample_metadata, sample_chapters)
    data = json.loads(result)
    
    scenes = data["chapters"][0]["scenes"]
    
    # Check first scene
    scene1 = scenes[0]
    assert scene1["scene_num"] == 1
    assert scene1["scene_type"] == "action"
    assert scene1["word_count"] == 12
    assert "protagonist rushed through" in scene1["content"]


# ------------------------------------------------------------------ #
# Export dispatcher tests                                              #
# ------------------------------------------------------------------ #


def test_export_dispatcher_txt(exporter, sample_metadata, sample_chapters):
    """Test export dispatcher routes to plain text."""
    result = exporter.export("txt", sample_metadata, sample_chapters)
    assert "THE TEST BOOK" in result
    assert "TABLE OF CONTENTS" in result


def test_export_dispatcher_text(exporter, sample_metadata, sample_chapters):
    """Test export dispatcher accepts 'text' format."""
    result = exporter.export("text", sample_metadata, sample_chapters)
    assert "THE TEST BOOK" in result


def test_export_dispatcher_plain(exporter, sample_metadata, sample_chapters):
    """Test export dispatcher accepts 'plain' format."""
    result = exporter.export("plain", sample_metadata, sample_chapters)
    assert "THE TEST BOOK" in result


def test_export_dispatcher_md(exporter, sample_metadata, sample_chapters):
    """Test export dispatcher routes to markdown."""
    result = exporter.export("md", sample_metadata, sample_chapters)
    assert "# The Test Book" in result
    assert "## Table of Contents" in result


def test_export_dispatcher_markdown(exporter, sample_metadata, sample_chapters):
    """Test export dispatcher accepts 'markdown' format."""
    result = exporter.export("markdown", sample_metadata, sample_chapters)
    assert "# The Test Book" in result


def test_export_dispatcher_json(exporter, sample_metadata, sample_chapters):
    """Test export dispatcher routes to JSON."""
    result = exporter.export("json", sample_metadata, sample_chapters)
    data = json.loads(result)
    assert "metadata" in data
    assert "chapters" in data


def test_export_dispatcher_case_insensitive(exporter, sample_metadata, sample_chapters):
    """Test export dispatcher is case-insensitive."""
    result_upper = exporter.export("TXT", sample_metadata, sample_chapters)
    result_mixed = exporter.export("Txt", sample_metadata, sample_chapters)
    
    assert "THE TEST BOOK" in result_upper
    assert "THE TEST BOOK" in result_mixed


def test_export_dispatcher_strips_whitespace(exporter, sample_metadata, sample_chapters):
    """Test export dispatcher strips whitespace from format."""
    result = exporter.export("  txt  ", sample_metadata, sample_chapters)
    assert "THE TEST BOOK" in result


def test_export_dispatcher_invalid_format(exporter, sample_metadata, sample_chapters):
    """Test export dispatcher raises error for invalid format."""
    with pytest.raises(ValueError) as exc_info:
        exporter.export("pdf", sample_metadata, sample_chapters)
    
    assert "Unsupported export format" in str(exc_info.value)
    assert "pdf" in str(exc_info.value)
    assert "txt" in str(exc_info.value)
    assert "md" in str(exc_info.value)
    assert "json" in str(exc_info.value)


# ------------------------------------------------------------------ #
# Integration tests                                                    #
# ------------------------------------------------------------------ #


def test_full_export_workflow_all_formats(exporter, sample_chapters):
    """Test complete export workflow for all formats."""
    # Calculate metadata using BookExporter methods
    prologue = "This is a test prologue with some words."
    epilogue = "This is a test epilogue with some words."
    
    total_word_count = BookExporter.calculate_word_count(
        prologue, sample_chapters, epilogue
    )
    reading_time = BookExporter.calculate_reading_time(total_word_count)
    toc = BookExporter.generate_table_of_contents(
        sample_chapters,
        include_prologue=True,
        include_epilogue=True,
    )
    
    # Create metadata
    metadata = BookMetadata(
        title="Integration Test Book",
        author_attribution="Generated by SCRIPTY",
        genre="Test Fiction",
        total_word_count=total_word_count,
        chapter_count=len(sample_chapters),
        scene_count=sum(len(ch.scenes) for ch in sample_chapters),
        reading_time_minutes=reading_time,
        table_of_contents=toc,
        generation_timestamp=datetime.now(timezone.utc),
    )
    
    # Export in all formats
    txt_result = exporter.export("txt", metadata, sample_chapters, prologue, epilogue)
    md_result = exporter.export("md", metadata, sample_chapters, prologue, epilogue)
    json_result = exporter.export("json", metadata, sample_chapters, prologue, epilogue)
    
    # Verify all exports contain key content
    # Plain text export uppercases the title in the title block
    assert "INTEGRATION TEST BOOK" in txt_result
    assert "# Integration Test Book" in md_result
    
    json_data = json.loads(json_result)
    assert json_data["metadata"]["title"] == "Integration Test Book"
    assert json_data["prologue"] == prologue
    assert json_data["epilogue"] == epilogue


def test_export_without_optional_sections(exporter, sample_chapters):
    """Test export works without prologue and epilogue."""
    # Calculate metadata
    total_word_count = BookExporter.calculate_word_count(None, sample_chapters, None)
    reading_time = BookExporter.calculate_reading_time(total_word_count)
    toc = BookExporter.generate_table_of_contents(
        sample_chapters,
        include_prologue=False,
        include_epilogue=False,
    )
    
    metadata = BookMetadata(
        title="No Prologue/Epilogue Book",
        author_attribution="Generated by SCRIPTY",
        genre="Test Fiction",
        total_word_count=total_word_count,
        chapter_count=len(sample_chapters),
        scene_count=sum(len(ch.scenes) for ch in sample_chapters),
        reading_time_minutes=reading_time,
        table_of_contents=toc,
        generation_timestamp=datetime.now(timezone.utc),
    )
    
    # Export without prologue/epilogue
    txt_result = exporter.export("txt", metadata, sample_chapters)
    md_result = exporter.export("md", metadata, sample_chapters)
    json_result = exporter.export("json", metadata, sample_chapters)
    
    # Verify exports work
    # Plain text export uppercases the title in the title block
    assert "NO PROLOGUE/EPILOGUE BOOK" in txt_result
    assert "# No Prologue/Epilogue Book" in md_result
    
    json_data = json.loads(json_result)
    assert json_data["prologue"] is None
    assert json_data["epilogue"] is None


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
